version: '3.8'
services:
  db-agenda:
    image: postgres:11.19-alpine
    container_name: db-agenda
    restart: always
    environment:
      POSTGRES_PASSWORD: "p0stgr3s"
      POSTGRES_DB: "agenda"
    ports:
      - 5432:5432
    volumes:
      - ~/volumes/postgres:/var/lib/postgresql/data
        
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 9090:8080
  
  api-agenda:
    image: balmeida80/api-agenda:1.0
    container_name: api-agenda
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db-agenda
    ports:
      - 3000:3000
    env_file:
      - .env
